FROM golang:1.22 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -v -o migrator ./cmd

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/migrator .
COPY --from=builder /app/config ./config
COPY --from=builder /app/migrations ./migrations
CMD ["./migrator", "migrate", "up"]