
name: Terraform
run-name: ${{ github.actor }} is destroying by terraform

on:
  push:
    branches: [ "main" ]

jobs:
  apply:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    environment: terraform-destroy
    defaults:
      run:
        working-directory: ./tf
    steps:

    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      run: terraform init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'tf'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_KEY }}
        
    - name: Terraform validate
      run: terraform validate

    - name: Terraform Destroy
      run: terraform destroy -var db_username="${{ secrets.DB_USERNAME }}" -var db_password="${{ secrets.DB_PASSWORD }}" -var my_ip="${{ secrets.MY_IP }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'tf'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_KEY }}